<?php

use Illuminate\Database\Seeder;

class SongsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('songs')->insert([
            ['album_id' => 1, 'name' => 'Время есть, а денег нет'],
            ['album_id' => 1, 'name' => 'Просто хочешь ты знать'],
            ['album_id' => 1, 'name' => 'Алюминиевые огурцы'],
            ['album_id' => 1, 'name' => 'Солнечные дни'],
            ['album_id' => 1, 'name' => 'Бездельник'],
            ['album_id' => 1, 'name' => 'Бездельник 2'],
            ['album_id' => 1, 'name' => 'Электричка'],
            ['album_id' => 1, 'name' => 'Восьмиклассница'],
            ['album_id' => 1, 'name' => 'Мои друзья'],
            ['album_id' => 1, 'name' => 'Ситар играл'],
            ['album_id' => 1, 'name' => 'Дерево'],
            ['album_id' => 1, 'name' => 'Когда-то ты был битником'],
            ['album_id' => 1, 'name' => 'На кухне'],
            ['album_id' => 1, 'name' => 'Я — асфальт'],

            ['album_id' => 2, 'name' => 'Троллейбус'],
            ['album_id' => 2, 'name' => 'Камчатка'],
            ['album_id' => 2, 'name' => 'Транквилизатор'],
            ['album_id' => 2, 'name' => 'Я иду по улице'],
            ['album_id' => 2, 'name' => 'Дождь для нас'],
            ['album_id' => 2, 'name' => 'Пора'],
            ['album_id' => 2, 'name' => 'Каждую ночь'],
            ['album_id' => 2, 'name' => 'Без десяти'],
            ['album_id' => 2, 'name' => 'Музыка волн'],
            ['album_id' => 2, 'name' => 'Саша'],
            ['album_id' => 2, 'name' => 'Хочу быть с тобой'],
            ['album_id' => 2, 'name' => 'Генерал'],
            ['album_id' => 2, 'name' => 'Стань птицей'],
            ['album_id' => 2, 'name' => 'Сельва'],
            ['album_id' => 2, 'name' => 'Я хочу быть кочегаром'],

            ['album_id' => 3, 'name' => 'Последний герой'],
            ['album_id' => 3, 'name' => 'Каждую ночь'],
            ['album_id' => 3, 'name' => 'Транквилизатор'],
            ['album_id' => 3, 'name' => 'Сюжет для новой песни'],
            ['album_id' => 3, 'name' => 'Гость'],
            ['album_id' => 3, 'name' => 'Камчатка'],
            ['album_id' => 3, 'name' => 'Ария Мистера Х'],
            ['album_id' => 3, 'name' => 'Троллейбус'],
            ['album_id' => 3, 'name' => 'Растопите снег'],
            ['album_id' => 3, 'name' => 'Дождь для нас'],
            ['album_id' => 3, 'name' => 'Хочу быть с тобой'],
            ['album_id' => 3, 'name' => 'Генерал'],
            ['album_id' => 3, 'name' => 'Прогулка романтика'],
            ['album_id' => 3, 'name' => 'Танкисты'],
            ['album_id' => 3, 'name' => 'Анаша'],
            ['album_id' => 3, 'name' => 'Постой, паровоз'],

            ['album_id' => 4, 'name' => 'Это не любовь'],
            ['album_id' => 4, 'name' => 'Весна'],
            ['album_id' => 4, 'name' => 'Уходи'],
            ['album_id' => 4, 'name' => 'Город'],
            ['album_id' => 4, 'name' => 'Проснись'],
            ['album_id' => 4, 'name' => 'Ты выглядишь так несовременно'],
            ['album_id' => 4, 'name' => 'Я объявляю свой дом'],
            ['album_id' => 4, 'name' => 'Саша'],
            ['album_id' => 4, 'name' => 'Верь мне'],
            ['album_id' => 4, 'name' => 'Дети проходных дворов'],
            ['album_id' => 4, 'name' => 'Музыка волн'],
            ['album_id' => 4, 'name' => 'Разреши мне'],
            ['album_id' => 4, 'name' => 'Стишок'],
            ['album_id' => 4, 'name' => 'Прохожий'],

            ['album_id' => 5, 'name' => 'Видели ночь'],
            ['album_id' => 5, 'name' => 'Фильмы'],
            ['album_id' => 5, 'name' => 'Твой номер'],
            ['album_id' => 5, 'name' => 'Танец'],
            ['album_id' => 5, 'name' => 'Ночь'],
            ['album_id' => 5, 'name' => 'Последний герой'],
            ['album_id' => 5, 'name' => 'Жизнь в стеклах'],
            ['album_id' => 5, 'name' => 'Мама анархия'],
            ['album_id' => 5, 'name' => 'Звезды останутся здесь'],
            ['album_id' => 5, 'name' => 'Игра'],
            ['album_id' => 5, 'name' => 'Мы хотим еще танцевать'],

            ['album_id' => 6, 'name' => 'Группа крови'],
            ['album_id' => 6, 'name' => 'Закрой за мной двер, я ухожу'],
            ['album_id' => 6, 'name' => 'Война'],
            ['album_id' => 6, 'name' => 'Спокойная ночь'],
            ['album_id' => 6, 'name' => 'Маша, мы все сошли с ума'],
            ['album_id' => 6, 'name' => 'Бошетунмай'],
            ['album_id' => 6, 'name' => 'В наших глазах'],
            ['album_id' => 6, 'name' => 'Попробуй спеть вместе со мной'],
            ['album_id' => 6, 'name' => 'Прохожий'],
            ['album_id' => 6, 'name' => 'Дальше действовать будем мы'],
            ['album_id' => 6, 'name' => 'Легенда'],

            ['album_id' => 7, 'name' => 'Песня без слов'],
            ['album_id' => 7, 'name' => 'Звезда по имени Солнце'],
            ['album_id' => 7, 'name' => 'Невеселая песня'],
            ['album_id' => 7, 'name' => 'Сказка'],
            ['album_id' => 7, 'name' => 'Место для шага вперед'],
            ['album_id' => 7, 'name' => 'Пачка сигарет'],
            ['album_id' => 7, 'name' => 'Стук'],
            ['album_id' => 7, 'name' => 'Печаль'],
            ['album_id' => 7, 'name' => 'Апрель'],

            ['album_id' => 8, 'name' => 'Хочу перемен!'],
            ['album_id' => 8, 'name' => 'Электричка'],
            ['album_id' => 8, 'name' => 'Война'],
            ['album_id' => 8, 'name' => 'Троллейбус'],
            ['album_id' => 8, 'name' => 'Печаль'],
            ['album_id' => 8, 'name' => 'Последний герой'],
            ['album_id' => 8, 'name' => 'Группа крови'],
            ['album_id' => 8, 'name' => 'Мама, мы все тяжело больны'],
            ['album_id' => 8, 'name' => 'В наших глазах'],
            ['album_id' => 8, 'name' => 'Спокойная ночь'],

            ['album_id' => 9, 'name' => 'Кончится лето'],
            ['album_id' => 9, 'name' => 'Красно-желтые дни'],
            ['album_id' => 9, 'name' => 'Нам с тобой'],
            ['album_id' => 9, 'name' => 'Звезда'],
            ['album_id' => 9, 'name' => 'Кукушка'],
            ['album_id' => 9, 'name' => 'Когда твоя девушка больна'],
            ['album_id' => 9, 'name' => 'Муравейник'],
            ['album_id' => 9, 'name' => 'Следи за собой'],
            ['album_id' => 9, 'name' => 'Сосны на морском берегу'],
            ['album_id' => 9, 'name' => 'Завтра война'],
        ]);
    }
}
